# Generated by Django 5.0.6 on 2024-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
