# Generated by Django 5.0.6 on 2024-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
